/** Decision-maker copy — G1 office shell + DM_INBOX_COPY_FIELD_MAP_v1. */
export const zhDM = {
  officeTitle: "AI 办公室",
  officeLede: "同事在工位上干活。你只在「待我拍板」出现时进来。",
  openInbox: "查看待我拍板",
  inboxTitle: "待办",
  inboxCount: (n: number) => (n > 0 ? `待办 · ${n}` : "待办"),
  desksEntry: "工位一览",
  desksHint: "只读投影。开跑不依赖打开这一页或画布。",
  empty: "此刻没有待办。安静是正常的。",
  filterReady: "要你决定",
  filterDecided: "已决定",
  inboxLead: "下面每张卡都过了硬门禁检查，可以拍板。",
  untitledGoal: "未命名目标",
  whyReady: "证据已齐，等你拍板",
  whyMissing: "还不能过，先看缺什么",
  missingTitle: "还差",
  evidenceLine: "同事已交：摘要 / 产物链接",
  pass: "通过",
  revise: "打回重做",
  defer: "稍后处理",
  badge: "待你决定",
  ruleDeliver: "规则：交付验收",
  readyRel: (when: string) => `就绪 · ${when}`,
  confirmPassTitle: "确认通过？",
  confirmPassBody: "通过后，这张硬门禁记为同意。系统按规则继续；不会因为有人说「好了」就过关。",
  confirmPass: "确认通过",
  cancel: "取消",
  passOk: "已通过。",
  reviseOk: "已打回，同事会再交一版。",
  deferOk: "已搁下，需要时还会出现。",
  conflict: "别人刚处理过这张，已帮你刷新。",
  reviseTitle: "打回重做",
  reviseSameDesk: "让同一工位再跑一版",
  reviseStructural: "这是结构问题，要换任务边界",
  reviseNote: "想改的方向（可选）",
  confirmRevise: "确认打回",
} as const;

export const MISSING_ZH: Record<string, string> = {
  summary_md: "还差：结论摘要",
  summary: "还差：结论摘要",
  "evidence:summary_md": "还差：结论摘要",
  artifact_uri: "还差：可打开的产物",
  artifact: "还差：可打开的产物",
  "evidence:artifact_uri": "还差：可打开的产物",
  github_pr_draft: "还差：合并请求仍是草稿",
  "github_pr draft": "还差：合并请求仍是草稿",
  github_checks: "还差：检查未全部通过",
};
