/** Inbox chrome: DM_INBOX_COPY_FIELD_MAP_v1. Office landing: CLICK_FLOW §4 where compatible. */
export const zhDM = {
  officeTitle: "AI 办公室",
  officeSub: "同事在工位上干活。你只在「待我拍板」出现时进来。",
  todoChip: "待办",
  todoChipCount: (n: number) => `待办 · ${n}`,
  rosterWeak: "工位一览",
  boardTitle: "待我拍板",
  emptyExact: "此刻没有待办。安静是正常的。",
  whyReady: "证据已齐，等你拍板",
  whyMissing: "还不能过，先看缺什么",
  missingTitle: "还差",
  missingUnknown: (key: string) => `还差：${key}`,
  missingMap: {
    "evidence:summary_md": "还差：结论摘要",
    summary_md: "还差：结论摘要",
    summary: "还差：结论摘要",
    "evidence:artifact_uri": "还差：可打开的产物",
    artifact_uri: "还差：可打开的产物",
    artifact: "还差：可打开的产物",
    "github_pr:is_draft=true": "还差：合并请求仍是草稿",
    github_pr_draft: "还差：合并请求仍是草稿",
    "evidence:pr": "还差：合并请求仍是草稿",
    "github_checks:conclusion=failure": "还差：检查未全部通过",
    github_checks: "还差：检查未全部通过",
  } as Record<string, string>,
  untitledGoal: "未命名目标",
  pass: "通过",
  revise: "打回重做",
  defer: "稍后处理",
  hardBadge: "硬门禁",
  statusChip: "待你决定",
  toastPass: "已通过。",
  toastRevise: "已打回，同事会再交一版。",
  toastDefer: "已搁下，需要时还会出现。",
  conflict: "别人刚处理过这张，已帮你刷新。",
  refresh: "刷新",
  details: "工程详情",
  ruleDeliver: "交付验收",
  ruleSafety: "安全门禁",
} as const;
