/** Decision-maker copy pack — DECISION_MAKER_CLICK_FLOW_v1 §1 / §4. */
export const zhDM = {
  officeTitle: "AI 办公室",
  officeSub: "同事在工位上干活。你只在「待我拍板」出现时进来。",
  ctaEmpty: "查看待我拍板",
  ctaCount: (n: number) => `待我拍板 · ${n}`,
  todoChip: "待办",
  todoChipCount: (n: number) => `待办 · ${n}`,
  rosterWeak: "工位一览",
  boardTitle: "待我拍板",
  filterDecide: "要你决定",
  filterDecided: "已决定",
  listHint: "下面每张卡都过了硬门禁检查，可以拍板。",
  emptyTitle: "此刻没有需要你拍板的事",
  emptyBody: "安静是正常的。同事填满工位后，卡片会自己出现在这里。",
  emptyFine: "不用去盯进度。完成以证据为准，不认口头说「好了」。",
  emptyExact: "此刻没有待办。安静是正常的。",
  whyReady: "证据已齐，等你过这一关",
  whyReadyAlt: "检查已齐，可以拍板",
  missingTitle: "还不能过，缺这些",
  missingShort: "还差",
  missingUnknown: (key: string) => `还缺：${key}`,
  missingMap: {
    "evidence:summary_md": "还缺一份结论摘要",
    summary_md: "还缺一份结论摘要",
    "evidence:artifact_uri": "还缺可打开的产物",
    artifact_uri: "还缺可打开的产物",
    "github_pr:is_draft=true": "相关合并请求还是草稿",
    "evidence:pr": "相关合并请求还是草稿",
    "github_checks:conclusion=success": "检查还没全部通过",
  } as Record<string, string>,
  pass: "通过",
  revise: "打回重做",
  defer: "以后再说",
  hardBadge: "硬门禁",
  statusChip: "待你决定",
  confirmTitle: "确认通过？",
  confirmBody: "通过后，这张硬门禁记为同意。系统按规则继续；不会因为有人说「好了」就过关。",
  confirmOk: "确认通过",
  confirmCancel: "取消",
  toastPass: "已通过 · 办公室少了一张待办",
  toastRevise: "已打回，同事会再交一版。",
  toastDefer: "已搁下，需要时还会出现。",
  conflict: "别人刚拍过，已为你刷新",
  reviseTitle: "打回重做",
  reviseSame: "让同一工位再跑一版",
  reviseStructural: "这是结构问题，要换任务边界",
  reviseNote: "想改的方向（可选）",
  reviseConfirm: "确认打回",
  details: "工程详情",
  ruleDeliver: "交付验收",
  ruleSafety: "安全门禁",
  outputSummary: "同事已交：摘要 / 产物链接",
} as const;

export type ZhDM = typeof zhDM;
