export { HarnessError, isHarnessError } from "./errors";
export {
  BRIEF_FORBIDDEN_KEYS,
  BriefV1Schema,
  BudgetSchema,
  EVIDENCE_KINDS,
  parseBriefOrThrow,
  parseBriefV1,
  parseBudget,
  type BriefV1,
  type Budget,
  type EvidenceKind,
} from "./brief";
export {
  ROLES,
  DIALS,
  MCP_TOOL_NAMES,
  MCP_HTTP_TOOL_NAMES,
  MCP_ENTRY_HEADER,
  MCP_ENTRY_VALUE,
  isBotCompletionWritePath,
  assertMcpEntry,
  parseBearer,
  parseRole,
  requireRole,
  requirePoolAccess,
  assertNoPlaintextCredentials,
  assertSecretRef,
  redactPayload,
  signJwt,
  verifyJwt,
  jwtSecret,
  type Actor,
  type Role,
  type Dial,
  type JwtClaims,
} from "./rbac";
export { WEBHOOK_SKEW_SECONDS, signHarnessWebhook, verifyHarnessWebhook } from "./hmac";
export { schema } from "./schema";
export { SCHEMA_SQL, SCHEMA_VERSION } from "./schema-sql";
export { applySchema, closeHarness, createHarness, type Harness, type Db } from "./db";
export {
  attachEvidence,
  createExceptionGrant,
  createGoal,
  createPool,
  decideGate,
  dispatchAssignment,
  fillAssignment,
  getAdminFreeze,
  getAssignment,
  getGoal,
  getRun,
  listFillSlots,
  listGoals,
  health,
  listAudit,
  listEventsAfter,
  listGateInstances,
  listGithubSnapshots,
  listOutbox,
  listPools,
  outboxStats,
  policyCheck,
  publishOutbox,
  reconcileCursorRuns,
  recordGithubSnapshot,
  syncCursorAgentRuns,
  workerTick,
  setAdminFreeze,
  setGoalDial,
  assertAdminNotFrozen,
  assertNoClientStatusWrite,
} from "./services";
export {
  listDesks,
  recordHeartbeat,
  DESK_STATUS,
  FAKE_SEED_DESK_NAMES,
  HEARTBEAT_TTL_SECONDS,
  HEARTBEAT_TTL_MIN,
  HEARTBEAT_TTL_MAX,
  humanDeskName,
  isFakeSeedDeskName,
  type DeskPresence,
  type HeartbeatInput,
} from "./desks";
export type { FillSlot } from "./services";
export { PolicyCheckResponse, advisoryBlocksDispatch } from "./policy-response";
export { AUTHORITY_ACTIONS, checkPolicy } from "@harness/policy";
